### ISSUE TITLE
No of Child Buttons

### ISSUE THREAD

**Issue by rahulsimpact** [nobitagit/material-floating-button#3]
How can I change the number of child buttons?
I want 5 but am having difficulty in doing so.

**Comment by nobitagit** [comment]
Supposing you have already installed Grunt and successfully run:

``` js
npm install
```

the steps you need to follow are:
- Add the appropriate number of child buttons in your html.
- Open the file `_customise.scss` and specify the number of buttons you need, in your case 5:

``` sass
$number-of-child-buttons: 5;
```

Save and run `grunt sass` or `grunt watch-css`. If you're not using the provided grunt tasks you can also process the SCSS on your own in your preferred way, obviously.

This way you should be good to go.
Let me know if you need any more help. Cheers.

**Comment by rahulsimpact** [comment]
Hey Nobita,

Thanks for your reply.
Actually I have never worked with grunt or node js which is why i am having problem in customizing.
I tried it with nodejs after watching some tutorial but I could not make it.

Is there a simple way or I have to learn grunt for this?

**Comment by nobitagit** [comment]
Actually in this case it's not a matter of learning Grunt, but just to manage to get it installed, as in this project everything is already configured to work out-of-the-box just by running a simple command.

Anyways, you can certainly do without. Do you have a way to compile files from SCSS to CSS or you work straight from CSS?

**Comment by rahulsimpact** [comment]
I work straight from css

**Comment by nobitagit** [comment]
Uhm.. let's see if this can help.

Head over to [this link](http://sassmeister.com/gist/6abf9c5d8389bfdcea6b).
On the the left you have the current SCSS full source, on the right the resulting compiled CSS. It's already configured for 5 buttons. If that's ok you can simply copy the CSS, otherwise tweak the variables in the SCSS and it will be compiled instantly.

Mind that this is the _current_ source, so if you forked/cloned before today's last commit you'll want to pull in the changes via git or fork/clone a fresh copy as the API has been changed today.

**Comment by rahulsimpact** [comment]
Thanks for the Help :100:  :+1: and a  :hamburger:

**Comment by nobitagit** [comment]
Haha... cheers mate!
